version: '3'
services:

  # Neo4j service
  neo4j:
    image: neo4j:4.0.6-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - .:/source
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/admin"
    container_name: "fdw-neo4j"
    
  legacy:
    image: neo4j:3.5.14-enterprise
    ports:
      - "17474:7474"
      - "17687:7687"
    volumes:
      - .:/source
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/admin"
    container_name: "fdw-legacy-neo4j"

  # Custom postgres from dokerfile
  postgres:
    build:
      context: .
      dockerfile: ./scripts/docker/postgres/Dockerfile
    volumes:
          - .:/source
    container_name: "fdw-pg"
