version: "3"
services:
  # Neo4j service
  neo4j:
    image: neo4j:${NEO4J_VERSION}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - .:/source
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/admin"
    container_name: "fdw-neo4j"
  # Custom postgres from dokerfile
  postgres:
    build:
      context: .
      dockerfile: ./scripts/docker/postgres/Dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
        - PYTHON_VERSION=${PYTHON_VERSION}
        - MULTICORN_VERSION=${MULTICORN_VERSION}
    volumes:
      - .:/source
    container_name: "fdw-pg"
